### ISSUE TITLE
Can this stack read the wheel encoder data of DFRobot?

### ISSUE THREAD

**Issue by somebodyus** [skohlbr/simple_2wd_robot#2]
Can this stack read the wheel encoder data of DFRobot?
Especially the **DFRobot MiniQ** with **DFRobot Mini Encoder Kit**.

**Comment by skohlbr** [comment]
Only open-loop control using two different motor shields is supported so far as documented here: https://github.com/skohlbr/simple_2wd_robot/wiki

It would be relatively easy to add support for reading encoders if some kind of Arduino code snippet is available already, however. In that case, a publisher that writes encoder data out to the ROS world via rosserial would have to be added, too.
