### ISSUE TITLE
What is the source for speed and angRate?  

### ISSUE THREAD

**Issue by jones5322** [skohlbr/simple_2wd_robot#3]
I'm a newbie trying to teach myself ROS for a skid steer project and "simple_2wd_robot" looks like a great platform for me to start my education.....My question is where is the data coming from for speed and angRate?  

void twistCallback(const geometry_msgs::TwistConstPtr twist)
  {
    float speed = twist->linear.x;
    float angRate = twist->angular.z;
    
    updateCommand(speed, angRate);
  }

**Comment by skohlbr** [comment]
The speed and angular rate are set from the Twist message that comes in as the argument for the callback you quoted.
